# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeTestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
    pod 'AFNetworking', '0.9.1'
  # Pods for ReactNativeTestProject

  target 'ReactNativeTestProjectTests' do
    inherit! :complete
    # Pods for testing
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
